DoctorAIWebApp/
│
├── config.toml            # Your config file
├── doctor_icon.ico         # Icon file uploaded to the repository
├── DoctorWebApp.py         # Your app file


[theme]
base="dark"
